// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
         // Use Web options for Linux to support hybrid/dev environment
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDgDZJwGa8GDmI6WLLnkVqU-8mJ0UcWqY',
    appId: '1:903290695559:web:65a45603e32ca12fd36d22',
    messagingSenderId: '903290695559',
    projectId: 'easytaskflow',
    authDomain: 'easytaskflow.firebaseapp.com',
    storageBucket: 'easytaskflow.firebasestorage.app',
    measurementId: 'G-GWLK7V7H7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyX3h266JnSduNziwp_-wNtFmKSf7lK4s',
    appId: '1:903290695559:android:1be15ec288c3b5e7d36d22',
    messagingSenderId: '903290695559',
    projectId: 'easytaskflow',
    storageBucket: 'easytaskflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdWzBB-OfubSTqUf-mWx0vpw0zx9jB744',
    appId: '1:903290695559:ios:18c1fb3cbf2cc8b0d36d22',
    messagingSenderId: '903290695559',
    projectId: 'easytaskflow',
    storageBucket: 'easytaskflow.firebasestorage.app',
    iosBundleId: 'com.example.easyTaskFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdWzBB-OfubSTqUf-mWx0vpw0zx9jB744',
    appId: '1:903290695559:ios:18c1fb3cbf2cc8b0d36d22',
    messagingSenderId: '903290695559',
    projectId: 'easytaskflow',
    storageBucket: 'easytaskflow.firebasestorage.app',
    iosBundleId: 'com.example.easyTaskFlow',
  );
}
